"""add exercises and unmatched_exercise_terms tables

Revision ID: 5690543eea0b
Revises: bbcc693d9c8a
Create Date: 2026-07-31 12:06:06.887315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5690543eea0b'
down_revision: Union[str, None] = 'bbcc693d9c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pg_trgm is a standard Postgres contrib extension (ships in the normal
    # postgres image, unlike pgvector) - powers the fuzzy string-matching tier
    # of exercise-name matching. See plans/02-exercise-library-matching.md.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('needs_equipment', sa.Boolean(), nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unmatched_exercise_terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_name', sa.String(length=255), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unmatched_exercise_terms_raw_name'), 'unmatched_exercise_terms', ['raw_name'], unique=True)
    # ### end Alembic commands ###

    # Trigram GIN index for fuzzy similarity() lookups against exercises.name.
    # (aliases is a JSONB array, not a plain text column - matched against via
    # jsonb_array_elements_text in the matching pipeline, un-indexed since the
    # library is small enough that a sequential scan there is fine.)
    op.execute(
        "CREATE INDEX ix_exercises_name_trgm ON exercises USING gin (name gin_trgm_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_exercises_name_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unmatched_exercise_terms_raw_name'), table_name='unmatched_exercise_terms')
    op.drop_table('unmatched_exercise_terms')
    op.drop_table('exercises')
    # ### end Alembic commands ###
