"""add is_admin to users

Revision ID: bbcc693d9c8a
Revises: 3acb8aa572df
Create Date: 2026-07-31 10:14:48.864268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbcc693d9c8a'
down_revision: Union[str, None] = '3acb8aa572df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows to false; NOT NULL alone would
    # fail here since this table already has data in every real environment.
    op.add_column(
        'users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
